// src/framework-adapters/react/actions.ts
/**
 * Action hooks — useLogin, useRegister, useLogout, etc. Each returns
 * `{ run, data, error, loading, isIdle, reset }` so a component can:
 *
 *   const login = useLogin();
 *   <form onSubmit={() => login.run({email, password})}>
 *     {login.loading && <Spinner />}
 *     {login.error && <Banner error={login.error} />}
 *   </form>
 *
 * One generic factory drives every action; the named exports are
 * one-liners on top so consumers get IntelliSense for the right
 * argument types per action.
 */

import { useCallback, useState } from 'react';
import {
    ACTION_BINDINGS,
    type ActionName,
} from '../shared/action-bindings.js';
import {
    type ActionState,
    type Action,
    initialActionState,
    runAction,
} from '../shared/action-state.js';
import { useAuthClient } from './context.js';
import type { AuthClient } from '../../core/auth-client.js';

/**
 * Generic factory: wires an ActionName to an Action<TArgs, TResult>
 * hook. Each named hook below is a one-line call into this.
 */
function useAction<Name extends ActionName>(
    name: Name,
    explicitClient: AuthClient | undefined,
): Action<
    Parameters<ReturnType<(typeof ACTION_BINDINGS)[Name]>>,
    Awaited<ReturnType<ReturnType<(typeof ACTION_BINDINGS)[Name]>>>
> {
    type Op = ReturnType<(typeof ACTION_BINDINGS)[Name]>;
    type Result = Awaited<ReturnType<Op>>;
    type Args = Parameters<Op>;

    const ctxClient = useAuthClient();
    const client = explicitClient ?? ctxClient;
    const [state, setState] = useState<ActionState<Result>>(
        initialActionState as ActionState<Result>,
    );

    const run = useCallback(
        (...args: Args): Promise<Result> => {
            const bind = ACTION_BINDINGS[name] as (c: AuthClient) => (...a: Args) => Promise<Result>;
            const op = bind(client);
            return runAction(op, setState, args);
        },
        [client, name],
    );

    const reset = useCallback(() => {
        setState(initialActionState as ActionState<Result>);
    }, []);

    return { ...state, run, reset };
}

/* -----------------------------------------------------------------
 * Named hooks — one per action. Thin wrappers over useAction so
 * consumers get the right argument/result types via IntelliSense.
 * ----------------------------------------------------------------- */

export const useLogin = (client?: AuthClient) => useAction('login', client);
export const useRegister = (client?: AuthClient) => useAction('register', client);
export const useLogout = (client?: AuthClient) => useAction('logout', client);
export const useLogoutAll = (client?: AuthClient) => useAction('logoutAll', client);
export const useStartSso = (client?: AuthClient) => useAction('startSso', client);
export const useCompleteSso = (client?: AuthClient) => useAction('completeSso', client);
export const useRefreshTokens = (client?: AuthClient) => useAction('refresh', client);
export const useWhoami = (client?: AuthClient) => useAction('whoami', client);
export const useSetupTwoFactor = (client?: AuthClient) => useAction('setupTwoFactor', client);
export const useEnableTwoFactor = (client?: AuthClient) => useAction('enableTwoFactor', client);
export const useDisableTwoFactor = (client?: AuthClient) => useAction('disableTwoFactor', client);
export const useImpersonate = (client?: AuthClient) => useAction('impersonate', client);
export const useHardDeleteUser = (client?: AuthClient) => useAction('hardDeleteUser', client);

// src/framework-adapters/solid/actions.ts
/**
 * Solid action helpers — same lifecycle as the React/Preact hooks but
 * built on createSignal.
 *
 *   const login = createLogin();
 *   login.run({ email, password });
 *   <Show when={login.loading()}>Signing in…</Show>
 *   <Show when={login.error()}>{login.error()!.message}</Show>
 *
 * Each accessor (data, error, loading, isIdle) is reactive; reads
 * inside a Solid effect / JSX track automatically.
 */

import { type Accessor, createSignal } from 'solid-js';
import type { AuthClient } from '../../core/auth-client.js';
import {
    ACTION_BINDINGS,
    type ActionName,
} from '../shared/action-bindings.js';
import {
    type ActionState,
    initialActionState,
    runAction,
} from '../shared/action-state.js';
import { useAuthClient } from './context.js';

export interface SolidAction<TArgs extends unknown[], TResult> {
    /** Invoke the action. */
    run: (...args: TArgs) => Promise<TResult>;
    /** Clear data + error, flip back to idle. */
    reset: () => void;
    data: Accessor<TResult | null>;
    error: Accessor<Error | null>;
    loading: Accessor<boolean>;
    isIdle: Accessor<boolean>;
}

function createAction<Name extends ActionName>(
    name: Name,
    explicitClient: AuthClient | undefined,
): SolidAction<
    Parameters<ReturnType<(typeof ACTION_BINDINGS)[Name]>>,
    Awaited<ReturnType<ReturnType<(typeof ACTION_BINDINGS)[Name]>>>
> {
    type Op = ReturnType<(typeof ACTION_BINDINGS)[Name]>;
    type Result = Awaited<ReturnType<Op>>;
    type Args = Parameters<Op>;

    const client = explicitClient ?? useAuthClient();
    const [state, setState] = createSignal<ActionState<Result>>(
        initialActionState as ActionState<Result>,
    );

    const run = (...args: Args): Promise<Result> => {
        const bind = ACTION_BINDINGS[name] as (c: AuthClient) => (...a: Args) => Promise<Result>;
        const op = bind(client);
        return runAction(op, setState, args);
    };

    const reset = (): void => {
        setState(initialActionState as ActionState<Result>);
    };

    return {
        run,
        reset,
        data: () => state().data,
        error: () => state().error,
        loading: () => state().loading,
        isIdle: () => state().isIdle,
    };
}

/* -----------------------------------------------------------------
 * Named factories — Solid convention uses `create*` for primitive
 * factories (createSignal, createEffect, createMemo). We match.
 * ----------------------------------------------------------------- */

export const createLogin = (client?: AuthClient) => createAction('login', client);
export const createRegister = (client?: AuthClient) => createAction('register', client);
export const createLogout = (client?: AuthClient) => createAction('logout', client);
export const createLogoutAll = (client?: AuthClient) => createAction('logoutAll', client);
export const createStartSso = (client?: AuthClient) => createAction('startSso', client);
export const createCompleteSso = (client?: AuthClient) => createAction('completeSso', client);
export const createRefreshTokens = (client?: AuthClient) => createAction('refresh', client);
export const createWhoami = (client?: AuthClient) => createAction('whoami', client);
export const createSetupTwoFactor = (client?: AuthClient) => createAction('setupTwoFactor', client);
export const createEnableTwoFactor = (client?: AuthClient) => createAction('enableTwoFactor', client);
export const createDisableTwoFactor = (client?: AuthClient) => createAction('disableTwoFactor', client);
export const createImpersonate = (client?: AuthClient) => createAction('impersonate', client);
export const createHardDeleteUser = (client?: AuthClient) => createAction('hardDeleteUser', client);
